# Generated by Django 2.1.2 on 2018-10-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='createdate',
            field=models.DateTimeField(auto_now=True, verbose_name='创建日期'),
        ),
    ]
