# Generated by Django 2.1.2 on 2018-10-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_person_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='modifydate',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='person',
            name='createdate',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
