# Generated by Django 2.1.2 on 2018-10-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0004_auto_20181030_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
