# Generated by Django 2.1.2 on 2018-10-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0006_auto_20181031_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='Person.Teacher'),
        ),
    ]
