# Generated by Django 2.1.2 on 2018-11-01 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0008_person_headimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='file', verbose_name='课程附件')),
                ('createdate', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.Course')),
            ],
        ),
    ]
