# Generated by Django 2.1.2 on 2018-11-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0009_course_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(to='Person.Course', verbose_name='选修课程'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='Person.Teacher', verbose_name='授课老师'),
        ),
    ]
