# Generated by Django 2.1.2 on 2018-11-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0010_auto_20181101_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='upload', verbose_name='文件')),
                ('createby', models.CharField(max_length=50, verbose_name='上传人')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
        ),
    ]
