# Generated by Django 2.1.2 on 2018-11-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0011_person_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonForgetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, verbose_name='电子邮箱')),
                ('verificationcode', models.CharField(max_length=6, verbose_name='验证码')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
        ),
    ]
